name: CI
on: [push, pull_request]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system libs
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Simulate + preprocess + import check
        env: { PYTHONPATH: . }
        run: |
          python src/simulate_retail.py --out_dir data --start_date 2025-01-01 --days 30 --customers 200 --products 60 --stores 3
          python src/preprocess_sales.py --transactions data/raw/transactions.csv --visits data/raw/visits.csv --out data/raw/daily_sales.csv
          python - <<'PY'
          import importlib
          for m in ['src.api','src.train_models','streamlit_app.app']:
              importlib.import_module(m); print('✅', m, 'imported')
          PY
